import { type FC, type ReactNode } from "react";
import { ArrowRight, Building2, LineChart, Lock, MessageSquareQuote, QrCode, ShieldAlert, Sparkles, ThumbsUp, UserCheck } from "lucide-react";
import type { TrialDialogPlacement } from "@/components/book-demo-dialog";

export const HowItWorks: FC<{ onRequestTrial: (placement: TrialDialogPlacement) => void }> = ({ onRequestTrial }) => {
  const steps = [
    ["01", "Business Sets Up the Campaign", "Create QR campaign links for each location and place them where customers can easily find them.", QrCode, "Campaign setup"],
    ["02", "Customer Shares Honest Feedback", "In seconds, the customer chooses a 1–5 star rating and selects a few highlights about what stood out.", ThumbsUp, "Zero friction"],
    ["03", "AI Solves the Blank-Page Problem", "5-Star.AI drafts natural wording matching the customer’s chosen tone and language. No generic templates.", Sparkles, "Instant assistance"],
    ["04", "Customer Decides What to Post", "The customer reads, modifies, copies, or continues to Google. They maintain 100% control over every word.", UserCheck, "Customer in control"],
  ] as const;
  return <section id="how-it-works" className="py-20 lg:py-28 bg-[#090D1A] border-t border-[#162035]/80"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl mx-auto text-center space-y-4 mb-16"><div className="text-xs font-semibold uppercase tracking-wider text-blue-400">Workflow & Process</div><h2 className="repo-serif text-3xl sm:text-4xl lg:text-5xl text-[#F8FAFC]">How 5-Star.AI works</h2><p className="text-base sm:text-lg text-slate-300 leading-relaxed">A transparent, ethical loop that bridges the gap between satisfied customers and public Google reviews.</p></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">{steps.map(([num, title, desc, Icon, tag]) => <div key={num} className="relative rounded-2xl bg-[#0D1322] border border-[#1E293B] p-6 flex flex-col justify-between hover:border-[#2A3B5C]"><div><div className="flex items-center justify-between mb-5"><span className="font-mono text-2xl font-bold text-slate-500/70">{num}</span><div className="p-2.5 rounded-xl bg-blue-500/10 text-blue-400"><Icon className="w-5 h-5" /></div></div><h3 className="text-lg font-semibold text-white mb-2">{title}</h3><p className="text-xs sm:text-sm text-slate-300 leading-relaxed">{desc}</p></div><div className="mt-6 pt-4 border-t border-[#1A233A] text-xs text-slate-500 font-medium flex items-center justify-between"><span>{tag}</span><span className="text-blue-400 font-mono text-[11px]">Verified flow</span></div></div>)}</div><div className="mt-14 max-w-4xl mx-auto rounded-2xl bg-gradient-to-r from-[#0D1322] via-[#11182A] to-[#0D1322] border border-[#22304C] p-6 sm:p-8 flex flex-col sm:flex-row items-center justify-between gap-6"><div className="space-y-1.5 text-center sm:text-left"><h4 className="text-base font-semibold text-white">Ready to see the workflow live for your business?</h4><p className="text-xs sm:text-sm text-slate-300">Our specialists configure your first test campaign during your guided 7-day trial.</p></div><button onClick={() => onRequestTrial("final_cta")} data-testid="button-how-it-works-request-trial" className="shrink-0 inline-flex items-center gap-2 px-5 py-2.5 text-xs font-semibold text-white bg-[#1A73E8] hover:bg-[#1557B0] rounded-xl"><span>Request guided trial</span><ArrowRight className="w-3.5 h-3.5" /></button></div></div></section>;
};

export const Features: FC = () => (
  <section id="features" className="py-20 lg:py-28 bg-[#070A13]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl mx-auto text-center space-y-4 mb-16"><div className="text-xs font-semibold uppercase tracking-wider text-blue-400">System Capabilities</div><h2 className="repo-serif text-3xl sm:text-4xl lg:text-5xl text-[#F8FAFC]">Built for integrity.<br />Engineered for genuine results.</h2><p className="text-base sm:text-lg text-slate-300 leading-relaxed">Every feature is designed to support clear customer choices, thoughtful owner review, and practical review operations across locations and teams.</p></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-12 gap-6">
    <FeatureCard span="lg:col-span-7" icon={QrCode} tone="blue" label="Campaign Links" title="QR Campaign Links for Review Drafts" text="Invite customers at a natural moment with location-specific QR campaign links. Customers can open an editable AI-assisted draft without a separate app." footer="Works from a phone browser · Customer chooses what to share"><div className="mt-4 p-4 rounded-xl bg-[#090D18] border border-[#1A233A] grid grid-cols-3 gap-3 text-center">{["Open QR Link","Choose Highlights","Edit Before Sharing"].map((x) => <div key={x} className="p-3 rounded-lg bg-[#11182A]"><div className="text-xs font-medium text-white">{x}</div><div className="text-[11px] text-slate-400 mt-0.5">Customer-controlled flow</div></div>)}</div></FeatureCard>
    <FeatureCard span="lg:col-span-5" icon={ShieldAlert} tone="amber" label="Optional Service Recovery" title="Private Constructive Feedback" text="For 1–2 star ratings, customers may see an optional, dismissible private-feedback prompt. They can skip it and still continue to generate or open a public Google review draft." footer="Owner email alerts are attempted for active OWNER accounts"><div className="p-3.5 rounded-xl bg-amber-950/20 border border-amber-900/40 text-xs text-amber-200/90 leading-relaxed">Private feedback gives owners another way to listen. It does not block a customer from continuing with a public draft.</div></FeatureCard>
    <FeatureCard span="lg:col-span-4" icon={MessageSquareQuote} tone="purple" title="Thoughtful Review Replies" text="Responding to reviews signals that your business cares. Draft personalized, de-escalating, or appreciative responses tailored to your chosen brand tone." footer="Approved by owner before posting" />
    <FeatureCard span="lg:col-span-4" icon={LineChart} tone="emerald" title="Operational Insights & Trends" text="Track review velocity, top-mentioned service highlights, sentiment trends across locations, and response time metrics without inflated claims or vanity scoring." footer="Clean, exportable reporting data" />
    <FeatureCard span="lg:col-span-4" icon={Building2} tone="indigo" title="Team Access & Aggregate Analytics" text="Give team members role-based access and review aggregate business analytics across locations. Keep operational visibility focused on the people and data your business manages." footer="Team role permissions · Aggregate business analytics" id="for-agencies" />
  </div><div className="mt-12 p-6 rounded-2xl bg-[#090D18] border border-[#1E293B] flex flex-col sm:flex-row items-start sm:items-center gap-4 text-xs text-slate-400"><div className="p-2 rounded-lg bg-blue-500/10 text-blue-400 shrink-0"><Lock className="w-5 h-5" /></div><div><div className="font-semibold text-white">Designed for clear customer choice</div><p className="text-slate-300 leading-relaxed mt-0.5">Customers can edit their wording, choose whether to continue to Google, and skip optional private feedback. Owners review AI reply drafts before using them.</p></div></div></div></section>
);

const FeatureCard: FC<{ span: string; icon: typeof QrCode; tone: string; label?: string; title: string; text: string; footer: string; id?: string; children?: ReactNode }> = ({ span, icon: Icon, tone, label, title, text, footer, id, children }) => {
  const color = tone === "amber" ? "text-amber-400 bg-amber-500/10" : tone === "emerald" ? "text-emerald-400 bg-emerald-500/10" : tone === "purple" ? "text-purple-400 bg-purple-500/10" : tone === "indigo" ? "text-indigo-400 bg-indigo-500/10" : "text-blue-400 bg-blue-500/10";
  return <div id={id} className={`${span} rounded-2xl bg-[#0D1322] border border-[#1E293B] p-7 flex flex-col justify-between hover:border-[#2A3B5C]`}><div className="space-y-4"><div className="flex items-center justify-between"><div className={`p-2.5 rounded-xl ${color}`}><Icon className="w-6 h-6" /></div>{label && <span className="text-xs font-mono text-slate-500">{label}</span>}</div><h3 className="text-xl font-semibold text-white">{title}</h3><p className="text-sm text-slate-300 leading-relaxed">{text}</p>{children}</div><div className="mt-6 pt-4 border-t border-[#1A233A] text-xs text-slate-400">{footer}</div></div>;
};