import { LegalPage } from "./LegalPage";
import { PRIVACY_META } from "./route-meta";

const sections = [
  {
    title: "Who we are",
    body: (
      <>
        <p>
          ReviewMyStore.AI ("ReviewMyStore", "we", "us") provides a platform that helps businesses
          collect Google reviews from their customers via QR codes, NFC taps, and AI-assisted review
          drafting. This Privacy Policy explains what information we collect, how we use it, and the
          choices you have.
        </p>
        <p>
          This policy covers both business users who create an account with us and customers of
          those businesses who use a review link, QR code, or NFC tag powered by ReviewMyStore.
        </p>
      </>
    ),
  },
  {
    title: "Information we collect",
    body: (
      <>
        <p>
          <strong className="text-foreground">Account information.</strong> When a business signs
          up, we collect a name, email address, and business details such as business name, Google
          Business Profile link, and campaign settings.
        </p>
        <p>
          <strong className="text-foreground">Review drafting inputs.</strong> When a customer uses
          a review page, we process the keywords or short notes they choose to provide in order to
          generate a suggested review draft. Customers always see, edit, and approve the draft
          before anything is posted.
        </p>
        <p>
          <strong className="text-foreground">Usage and device data.</strong> We collect basic
          analytics about scans, taps, and page visits — such as timestamps, approximate location
          derived from IP address, browser type, and device type — to show businesses how their
          campaigns perform.
        </p>
        <p>
          <strong className="text-foreground">Communications.</strong> If you contact us or request
          a demo, we keep the information you submit so we can respond.
        </p>
      </>
    ),
  },
  {
    title: "How we use information",
    body: (
      <>
        <p>We use the information we collect to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Provide, operate, and improve the ReviewMyStore platform;</li>
          <li>Generate AI-assisted review drafts at the customer's request;</li>
          <li>Show businesses analytics about their review campaigns;</li>
          <li>Send service-related communications, such as account and security notices;</li>
          <li>Respond to support requests and demo inquiries;</li>
          <li>Detect and prevent fraud, spam, and abuse of the platform.</li>
        </ul>
        <p>We do not sell your personal information.</p>
      </>
    ),
  },
  {
    title: "AI-generated content",
    body: (
      <p>
        Review drafts are generated by third-party AI models based on the inputs a customer
        provides. Drafts are suggestions only: the customer reviews, edits, and decides whether to
        post. We do not post reviews on anyone's behalf, and we design the product so that only
        genuine customer experiences are shared.
      </p>
    ),
  },
  {
    title: "How we share information",
    body: (
      <>
        <p>We share information only in the following circumstances:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong className="text-foreground">Service providers</strong> that help us run the
            platform (hosting, authentication, email delivery, AI model providers), bound by
            confidentiality obligations;
          </li>
          <li>
            <strong className="text-foreground">The business you interacted with</strong> — a
            business can see aggregate campaign analytics, but not the content a customer typed
            unless the customer chooses to post it publicly;
          </li>
          <li>
            <strong className="text-foreground">Legal requirements</strong>, when required to comply
            with applicable law or valid legal process;
          </li>
          <li>
            <strong className="text-foreground">Business transfers</strong>, if we are involved in a
            merger, acquisition, or sale of assets.
          </li>
        </ul>
      </>
    ),
  },
  {
    title: "Data retention",
    body: (
      <p>
        We keep account information for as long as your account is active and as needed to comply
        with legal obligations. Campaign analytics are retained so businesses can track performance
        over time. You can request deletion of your account and associated data at any time by
        contacting us.
      </p>
    ),
  },
  {
    title: "Security",
    body: (
      <p>
        We use industry-standard safeguards to protect your information, including encryption in
        transit, access controls, and reputable infrastructure providers. No method of transmission
        or storage is completely secure, so we cannot guarantee absolute security.
      </p>
    ),
  },
  {
    title: "Your rights",
    body: (
      <p>
        Depending on where you live, you may have rights to access, correct, delete, or export your
        personal information, and to object to or restrict certain processing. To exercise any of
        these rights, email us at{" "}
        <a href="mailto:contact@reviewmystore.ai" className="text-primary hover:underline">
          contact@reviewmystore.ai
        </a>
        . We will respond within the timeframe required by applicable law.
      </p>
    ),
  },
  {
    title: "Children",
    body: (
      <p>
        ReviewMyStore is intended for business use and is not directed at children under 16. We do
        not knowingly collect personal information from children.
      </p>
    ),
  },
  {
    title: "Changes to this policy",
    body: (
      <p>
        We may update this Privacy Policy from time to time. When we do, we will revise the "Last
        updated" date above and, for material changes, notify account holders by email or an in-app
        notice.
      </p>
    ),
  },
  {
    title: "Contact us",
    body: (
      <p>
        Questions about this policy or our data practices? Email{" "}
        <a href="mailto:contact@reviewmystore.ai" className="text-primary hover:underline">
          contact@reviewmystore.ai
        </a>
        .
      </p>
    ),
  },
];

export default function Privacy() {
  return (
    <LegalPage
      badge="Legal"
      title="Privacy Policy"
      intro="How ReviewMyStore.AI collects, uses, and protects your information."
      lastUpdated="August 6, 2026"
      sections={sections}
      metaTitle={PRIVACY_META.title}
      metaDescription={PRIVACY_META.description}
      path="/privacy"
    />
  );
}
